misc
* remove unnecessary sudo's
* update usage
* cleaner verbose/non-verbose mode
* add do reboot

diff --git a/halium-install b/halium-install
--- a/halium-install
+++ b/halium-install
@@ -21,12 +21,8 @@ export DO_COPY_SSH_KEY=false
 export SSH_KEY=~/.ssh/id_rsa.pub
 export DO_ROOTFS=true
 export DO_AND_IMAGE=true
-
-function quiet () {
-	cat > /dev/null
-}
-
-out=quiet
+export OUT=/dev/null
+export DO_REBOOT=false
 
 # Include functions
 source $LOCATION/functions/misc.sh
@@ -74,7 +70,14 @@ while [ -n "$1" ] ; do
 		DO_ROOTFS=false
 		;;
 	"-v")
-		out="cat -"
+		OUT=/dev/stdout
+		;;
+	"-V")
+		OUT=/dev/stdout
+		set -xv
+		;;
+	"-b")
+		DO_REBOOT=true
 		;;
 	*)
 		break
@@ -119,6 +122,12 @@ if $DO_AND_IMAGE ; then
 	echo "Debug: Chosen android image is $AND_IMAGE"
 fi
 
+if [ $# -ge 1 ] ; then
+	echo "Error: Found unnecessary parameter \"$1\""
+	usage
+	exit 1
+fi
+
 # Check for missing dependencies
 if ! init_checks; then
 	exit
@@ -138,11 +147,11 @@ if $DO_ROOTFS ; then
 	case "$INSTALL_MODE" in
 	"img")
 		echo "I: Writing rootfs into mountable image"
-		convert_rootfs_to_img $IMAGE_SIZE 2>&1 | $out
+		convert_rootfs_to_img $IMAGE_SIZE >$OUT
 		;;
 	"dir")
 		echo "I: Extracting rootfs"
-		convert_rootfs_to_dir 2>&1 | $out
+		convert_rootfs_to_dir >$OUT
 		;;
 	esac
 
@@ -153,10 +162,10 @@ fi
 
 if $DO_AND_IMAGE ; then
 	echo "I: Writing android image into mountable image"
-	convert_androidimage 2>&1 | $out
+	convert_androidimage >$OUT
 
 	echo "I: Shrinking android image"
-	shrink_android_img
+	shrink_android_img >$OUT
 fi
 
 
@@ -175,7 +184,7 @@ case "$INSTALL_MODE" in
 	fi
 	;;
 "dir")
-	echo FIXME
+	echo "FIXME the dir mode does not support flashing only system.img and is probably broken now :( should it? if not, maybe an INSTALL_MODE=onlyandroidimg would make more sense ...." 
 	exit 1
 	echo "I: Pushing rootfs and android image to /data via ADB"
 
@@ -194,6 +203,11 @@ clean
 
 echo "I: Cleaning up device"
 clean_device
+
+if $DO_REBOOT ; then
+	echo "I: Rebooting device"
+	adb reboot
+fi
 
 echo "I: Finished successfully"
 
